### PR TITLE
removing unnecessary comment

### PR DESCRIPTION
**Pull request by allain**

### CODE REVIEW

**Comment by dominictarr** [comment]
this seems to say the same thing as before, can you describe what has been improved by this change?

**Comment by allain** [comment]
The comment was for a piece of code that had been moved up in the file. So,
the code it pertained to was no longer there.

Immediately following the deleted comment was a call to applyUpdate,making
it appear that the ignoring of the update was going to be handled by
applyUpdate.

**Comment by dominictarr** [comment]
thanks, that makes merging a much easier decision. this is sometimes hard to see what is going on just from looking at the diff.

**Comment by dominictarr** [comment]
merged into 5.6.11

**Pull request merged**
