### PR TITLE
remove the security subsystem

### PR DESCRIPTION
**Pull request by edef1c**
Scuttlebutt's security subsystem is in fact fairly useless, because
updates can simply be left out by malicious nodes, and because updates
must arrive in-order, it is possible to cause past messages to be
ignored if they have not reached the local node yet.
The security subsystem unnecessarily complicates the code, and provides
a false sense of security. Scuttlebutt must be used in trusted
environments for it to function correctly. Thus, I'm proposing removing the
security subsystem.

### CODE REVIEW

**Comment by paulkernfeld** [comment]
To me, the security system seems to be much better than nothing! My reasoning is that, although the security system is vulnerable to some types of DOS attacks (i.e. dropping messages), it still prevents message forging. Also, a malicious peer can't prevent you from downloading the missing messages from a good peer, right?

Maybe we could update the documentation to describe these security characteristics?

**Comment by dominictarr** [comment]
@paulkernfeld well, the security bit is also a experiment and I'm not really sure if anyone has ever used it. And anyway, it uses RSA and ed25519 would be way less overhead bandwidth.

**Comment by paulkernfeld** [comment]
Fair enough. Is the solution, then, to implement signing and verification as a layer on top of scuttlebutt? Or does it need to be baked into scuttlebutt itself?

**Comment by dominictarr** [comment]
the scuttlebutt feature that ruins security is how it GCs old data that is no longer needed. to be fully secure you'd need to keep everything forever - making it more like a signed chain. hmm, maybe there is a way you could do that efficiently that wouldn't require you to keep everything in memory?

merkle trees do a thing like this where you can leave out records, but provide a proof that it's still part of the same set.

you might also be interested in my new project, [secure-scuttlebutt](https://github.com/ssbc), it's a very different interface to scuttlebutt but works on the same basic protocol idea.

**Comment by paulkernfeld** [comment]
Oh, okay. Is it correct that scuttlebutt security only checks that messages are signed, but secure-scuttlebutt also prevents messages from being reordered or left out? Also it seems that secure-scuttlebutt does a nice trick by naming feeds by the hash of the public key.

Also, what is the relationship between scuttlebutt and secure-scuttlebutt? Is it possible to use all the subclasses (e.g. [crdt](https://github.com/dominictarr/crdt)) with secure-scuttlebutt?

**Comment by dominictarr** [comment]
@paulkernfeld hmm, there is probably a way you could do that! then you'd have cheap collaborative editing, etc!

**Comment by dominictarr** [comment]
you wouldn't use the scuttlebutt replication, but you could use the CRDT bit.

**Pull request closed without merging**
