### PR TITLE
Fixed style issue in readme

### PR DESCRIPTION
**Pull request by ArtskydJ**

### CODE REVIEW

**Comment by dominictarr** [comment]
Sorry I don't take pull requests for whitespace. BUT! if you want to satisfy your OCD and you can find *another* problem (a typo is acceptable) and add this to the PR. Then I will merge your whitespace.

**Comment by dominictarr** [comment]
oops, this wasn't a white space fix. but the problem was that you didn't include a description of what the PR actually did, which made it appear to be a pure whitespace change (which I got one time!) please ALWAYS include a description of what the fix is. It's never as obvious as it seems.

**Comment by dominictarr** [comment]
merged into 5.6.13

**Comment by ArtskydJ** [comment]
I'll keep that in mind, thanks!

**Comment by ArtskydJ** [comment]
Sorry for the confusion. :smiley:

**Pull request merged**
